apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mercedev
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: mercedev
        tier: backend
    spec:
      containers:
#      - name: redis
#        image: gcr.io/google_containers/redis:v1
#        resources:
#          requests:
#            cpu: 100m
#            memory: 100Mi
#        ports:
#        - containerPort: 6379
      - name: metrics
        image: 995121555896.dkr.ecr.us-east-1.amazonaws.com/cloudlock/svc-metrics:0.2.5
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8040
#      - name: db
#        image: gcr.io/google_containers/redis:v1
#        resources:
#          requests:
#            cpu: 100m
#            memory: 100Mi
#        ports:
#        - containerPort: 80
