apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: dev-nginx
  name: dev-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      run: dev-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: dev-nginx
    spec:
      containers:
      - image: nginx
        name: dev-nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}